source("https://bioconductor.org/biocLite.R")
biocLite("RBGL")
install.packages("graph")
library(graph)
install.packages("gRbase")
library(gRbase)
data(cad1, package='gRbase')
str(cad1) 
install.packages("bnlearn")
library(bnlearn)
cad.bn <-  hc(cad1)
cad.bn
biocLite("Rgraphviz")
plot(as(amat(cad.bn), "graphNEL"))
