install.packages("igraph")
library(igraph)
install.packages("ggm")
library(ggm)
dag <-DAG(g ~ x, h ~ x+f, f ~ b, x ~ l+d, d ~ c, c ~ a, l ~ y, y ~ b)
drawGraph(dag, adjust = FALSE)
dSep(dag, first="a", second="b", cond=c("x", "y"))
dSep(dag, first="a", second=c("b", "d"), cond=c("x", "y"))
dSep(dag, first="a", second="g", cond=NULL)
dSep(dag, first="a", second="g", cond="x")
