install.packages("MASS")
library(MASS)
require(stats); require(graphics)
swiss.x<- as.matrix(swiss[, -1])
swiss.dist<- dist(swiss.x)
swiss.mds<- isoMDS(swiss.dist)
plot(swiss.mds$points, type = "n")
text(swiss.mds$points, labels = as.character(1:nrow(swiss.x)))
swiss.sh <- Shepard(swiss.dist,  swiss.mds$points)
plot(swiss.sh, pch= ".")
lines(swiss.sh$x, swiss.sh$yf, type = "S", col="red")
